#Name: Michael Zhou
#UID:

default:
	gcc -D_POSIX_C_SOURCE -Wall -Wextra -g -std=c99 -o lab1a lab1a.c
clean:
	rm -rf lab1a *.tar.gz *.o

dist:
	tar -czf lab1a-804663317.tar.gz lab1a.c Makefile README
